/**
 * Cpp/include/main_window.h
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 * Qt MainWindow that is wired to the shared .ui file.
 *
 * The .ui file is compiled by AUTOUIC (CMake) into
 *   ui_main_window.h
 * which provides the Ui::MainWindow generated class.  The same
 * .ui file is loaded at runtime by Python/PySide6/QUiLoader.
 */
#pragma once

#include <QMainWindow>
#include <QVector>

#include "employee.h"
#include "scheduler.h"

// Generated by AUTOUIC from shared/ui/main_window.ui
QT_BEGIN_NAMESPACE
namespace Ui
{
    class MainWindow;
}
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow() override;

private slots:
    // Input tab
    void onAddEmployee();
    void onLoadDemo();
    void onClearAll();
    void onRemoveEmployee();
    void onBuildSchedule();
    // Menu
    void onAbout();

private:
    Ui::MainWindow *ui;
    QVector<Employee> employees_;
    Scheduler *scheduler_{nullptr};

    // UI helpers
    void applyStylesheet();
    void configureTableHeaders();
    void refreshEmployeeTable();
    void populateScheduleTab();
    void populateSummaryTab();
    void populateWarnings();
    void setStatus(const QString &msg, bool error = false);

    // Reads the ranked drag-list and strips the emoji prefix
    QStringList readPreferencesFromList() const;
};
